name: build

on:
  schedule:
    - cron:  '30 5 * */1 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Check Out Repo 
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./.devcontainer/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/classpad-dev-env:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  
        
